# Generated by Django 2.2.7 on 2019-11-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rclient', models.CharField(max_length=200, verbose_name='Rut del cliente')),
                ('nclient', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direccion Web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de adición')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created'],
            },
        ),
    ]
