# Generated by Django 2.2.7 on 2019-11-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fnac',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
