# Generated by Django 2.2.7 on 2019-11-14 03:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0002_project_fnac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='correo',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200, verbose_name='Correo electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
