# Generated by Django 2.2.7 on 2019-11-14 03:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0003_auto_20191113_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Numero de telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
