# Generated by Django 2.2.7 on 2019-11-20 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0007_auto_20191120_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='product',
            name='correo',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200, verbose_name='Correo electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fnac',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='nclient',
            field=models.CharField(default=1, max_length=200, verbose_name='Nombre del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Numero de telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rclient',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Rut del cliente'),
            preserve_default=False,
        ),
    ]
