# Generated by Django 2.2.7 on 2019-11-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0009_product_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
