# Generated by Django 2.2.7 on 2019-11-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0010_auto_20191120_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
