# Generated by Django 2.2.7 on 2019-11-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservadehoras', '0011_auto_20191120_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
    ]
